# Saved pandas tables

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback

In [1]:
df

DataFrame fallback